name: JailTracker
version: 1.0
main: com.flancraft.jailtracker.JailTracker
api-version: 1.20
commands:
  jail:
    description: Comando para enviar datos al panel y aplicar jail
    usage: /jail <jugador> <carcel> <tiempo> [motivo]
    permission: essentials.jail
  ban:
    description: Comando para banear y reportar
    usage: /ban <jugador> <motivo>
    permission: essentials.ban
  tempban:
    description: Tempban + registro web
    usage: /tempban <jugador> <tiempo> <motivo>
    permission: essentials.tempban
